---
version: '2'
services:
    mysql:
        image: mysql:5.7
        restart: always
        container_name: generatedata-mysql
        environment:
            MYSQL_ROOT_PASSWORD: P@ssw0rd
            MYSQL_DATABASE: generatedata_db
            MYSQL_USER: generatedata
            MYSQL_PASSWORD: P@ssw0rd
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - generatedata_data:/var/lib/mysql
    web:
        build: web
        restart: always
        container_name: generatedata
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            MYSQL_DB_HOSTNAME: mysql
            MYSQL_DB_USER: generatedata
            MYSQL_DB_PASSWORD: P@ssw0rd
            MYSQL_DB_NAME: generatedata_db
            MYSQL_DB_PORT: 3306
        ports:
            - 8080:80
        depends_on:
            - mysql
#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        container_name: phpmyadmin
#        environment:
#            - PMA_ARBITRARY=1
#        restart: always
#        ports:
#            - 8081:80
#        depends_on:
#            - mysql

volumes:
    generatedata_data:
        driver: local


