---
version: '3'
services:
    db1:
        image: mssql-2017
        build: db
        restart: always
        container_name: db1
        hostname: db1
        environment:
            SA_PASSWORD: P@ssw0rd
            MSSQL_PID: Developer
            ACCEPT_EULA: Y
            MSSQL_AGENT_ENABLED: 'true'
            MSSQL_ENABLE_HADR: 1
            MSSQL_BACKUP_DIR: '/backup'
            MSSQL_RPC_PORT: 135
            MSSQL_DTC_TCP_PORT: 51000
            TZ: Europe/Berlin
            LANG: en_US.UTF-8
            LANGUAGE: en_US:en
            LC_ALL: en_US.UTF-8
        volumes:
            - shared:/var/opt/mssql/shared
            - ./data/backup:/backup
        ports:
            - "10000:1444"
            - "10001:1433"
            - "20001:5022"
            - "30001:135"
            - "40001:51000"
        networks:
            - sqlserver-net
    db2:
        build: db
        image: mssql-2017
        restart: always
        container_name: db2
        hostname: db2
        environment:
            SA_PASSWORD: P@ssw0rd
            MSSQL_PID: Developer
            ACCEPT_EULA: Y
            MSSQL_AGENT_ENABLED: 'true'
            MSSQL_ENABLE_HADR: 1
            MSSQL_BACKUP_DIR: '/backup'
            MSSQL_RPC_PORT: 135
            MSSQL_DTC_TCP_PORT: 51000
            TZ: Europe/Berlin
            LANG: en_US.UTF-8
            LANGUAGE: en_US:en
            LC_ALL: en_US.UTF-8
        volumes:
            - shared:/var/opt/mssql/shared
            - ./data/backup:/backup
        ports:
            - "10002:1433"
            - "20002:5022"
            - "30002:135"
            - "40002:51000"
        networks:
            - sqlserver-net
networks:
    sqlserver-net:

volumes:
    shared:
