---
version: '2'
services:
    mysql:
        build: db
        restart: always
        container_name: phpipam-mysql
        environment:
            MYSQL_ROOT_PASSWORD: P@ssw0rd
            MYSQL_DATABASE: phpipam_db
            MYSQL_USER: phpipam
            MYSQL_PASSWORD: P@ssw0rd
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - phpipam_data:/var/lib/mysql
    phpipam:
        build: web
        restart: always
        container_name: phpipam
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            MYSQL_DB_HOSTNAME: mysql
            MYSQL_DB_USER: phpipam
            MYSQL_DB_PASSWORD: P@ssw0rd
            MYSQL_DB_NAME: phpipam_db
            MYSQL_DB_PORT: 3306
        ports:
            - 8080:80
        depends_on:
            - mysql
#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        container_name: phpmyadmin
#        environment:
#            - PMA_ARBITRARY=1
#        restart: always
#        ports:
#            - 8081:80
#        depends_on:
#            - mysql

volumes:
    phpipam_data:
        driver: local


