version: '2'
services:
    mysql:
        build: db
        restart: always
        container_name: guacamole_mysql
        environment:
            MYSQL_ROOT_PASSWORD: P@ssw0rd
            MYSQL_PASSWORD: P@ssw0rd
            MYSQL_USER: guac
            MYSQL_DATABASE: guacamole_db
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - guac-data:/var/lib/mysql
        networks:
            - guac
    guacd:
        image: glyptodon/guacd
        restart: always
        container_name: guacd
        volumes:
            - /etc/localtime:/etc/localtime:ro
        networks:
            - guac
    guac:
        image: glyptodon/guacamole
        restart: always
        container_name: guacamole
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            MYSQL_DATABASE: guacamole_db
            MYSQL_USER: guac
            MYSQL_PASSWORD: P@ssw0rd
            MYSQL_HOSTNAME: mysql
            MYSQL_PORT: 3306
            GUACD_PORT_4822_TCP_ADDR: guacd
            GUACD_PORT_4822_TCP_PORT: 4822
            GUACD_HOSTNAME: guacd
            GUACD_PORT: 4822
        ports:
            - "8080:8080"
        depends_on:
            - mysql
            - guacd
        networks:
            - guac
#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        container_name: phpmyadmin
#        environment:
#            - PMA_ARBITRARY=1
#        restart: always
#        ports:
#            - "8081:80"
#        depends_on:
#            - mysql
#        networks:
#            - guac

volumes:
    guac-data:
        driver: local

networks:
    guac:
        driver: bridge

