#
# Docker image for
#
# Personify SCIM Server - custom
#

FROM personify/personify-scim-server
LABEL maintainer "André Raabe <andre.raabe@gmail.com>"

ADD connector_database.json /tmp/connector_database.json

EXPOSE 8080

