CREATE DATABASE [klaros]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'klaros', FILENAME = N'/var/opt/mssql/data/klaros.mdf' , SIZE = 524288KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'klaros_log', FILENAME = N'/var/opt/mssql/data/klaros_log.ldf' , SIZE = 65536KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [klaros] SET COMPATIBILITY_LEVEL = 130
GO
ALTER DATABASE [klaros] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [klaros] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [klaros] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [klaros] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [klaros] SET ARITHABORT ON 
GO
ALTER DATABASE [klaros] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [klaros] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [klaros] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [klaros] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [klaros] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [klaros] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [klaros] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [klaros] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [klaros] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [klaros] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [klaros] SET  DISABLE_BROKER 
GO
ALTER DATABASE [klaros] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [klaros] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [klaros] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [klaros] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [klaros] SET  READ_WRITE 
GO
ALTER DATABASE [klaros] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [klaros] SET  MULTI_USER 
GO
ALTER DATABASE [klaros] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [klaros] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [klaros] SET DELAYED_DURABILITY = DISABLED 
GO
USE [klaros]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [klaros]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [klaros] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

